[package]
name = "day_12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils" }
anyhow = "1.0.66"
petgraph = "0.6.2"
